### PR TITLE
simplify code and fix a bug

### PR DESCRIPTION
**Pull request by Garnel**
1. simplify code when dealing with tail
2. fix a bug when tail_size is not zero, ( k1 << 16 | k1 >> 16 ) => ( k1 << 15 | k1 >> 17 )

### CODE REVIEW

**Comment by wc-duck** [comment]
Your change fails the unittests ( that were broken =/ ) I have checked in regenerated test-files that make the tests succeed.

I tested your changes with pymmh3.hash( 'apa' ) towards the c++ implementation running:
	uint32_t apa_hash;
	mmh3::MurmurHash3_x86_32( "apa", 3, 0, &apa_hash );

	printf("apa 0x%08X\n", apa_hash);

My old implementation returned the correct hash, yours didn't =/

**Comment by wc-duck** [comment]
When did you encounter the issue you tried to fix?

**Comment by Garnel** [comment]
I viewed the `MurmurHash3.inc` in your unittest, I notice that it's different from the code on [google code](https://code.google.com/p/smhasher/source/browse/trunk/MurmurHash3.cpp)

this line in `MurmurHash3_x86_32` should be
```cpp
k1 *= c1; k1 = ROTL32(k1,15); k1 *= c2; h1 ^= k1;
```

while in your `MurmurHash3.inc`, it is
```cpp
k1 *= c1; k1 = ROTL32(k1,16); k1 *= c2; h1 ^= k1;
```

That is where I made the change

**Comment by wc-duck** [comment]
Interesting... I must have an old MurmurHash3 src, I see that it has been fixed in the smhasher repos. I'll update the file and re-test your changes!

**Comment by wc-duck** [comment]
However it might take a few hours... family matters :)

**Comment by wc-duck** [comment]
I have updated MurmurHash3.inc and tested now and your changes still do not work, however if you change your == to >= in the if:s it work fine.
Do you want to make a fixed pull-request or do you want me to submit the code? If you make a new pull-request, please update MurmurHash3.inc and rebuild the unittest data.

**Comment by Garnel** [comment]
I update the MurmurHash3.inc and rebuild the unittest, and fix my stupid bug :)
It passes the unittest now

**Comment by wc-duck** [comment]
Great stuff... thanks for the fix.

**Pull request merged**
